# Generated by Django 3.2.25 on 2024-11-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_meal'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='quantity',
            field=models.IntegerField(default=3),
        ),
    ]
