# Generated by Django 3.2.25 on 2024-12-13 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_menu_meal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.meal'),
        ),
    ]
