# Generated by Django 3.2.25 on 2024-12-14 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='menu_day',
        ),
    ]
