# Generated by Django 3.2.25 on 2024-11-17 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_meal_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='meal',
            options={'verbose_name': 'Блюдо', 'verbose_name_plural': 'Блюда'},
        ),
    ]
