# Generated by Django 3.2.25 on 2024-11-25 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20241117_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='image',
            field=models.ImageField(upload_to='images', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='out',
            field=models.CharField(max_length=10, verbose_name='Выход'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='price',
            field=models.FloatField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='quantity',
            field=models.IntegerField(default=3, verbose_name='Количество'),
        ),
    ]
