# Generated by Django 5.0.7 on 2025-03-06 10:17

import apt_delivery_app.models.m_order
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apt_delivery_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='date',
            field=models.DateField(default=datetime.date(2025, 3, 7), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.TimeField(default=apt_delivery_app.models.m_order.get_default_created_at, verbose_name='Дата и время получения заказа'),
        ),
    ]
