# Generated by Django 5.1.1 on 2025-03-16 13:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apt_delivery_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='date',
            field=models.DateField(default=datetime.date(2025, 3, 17), verbose_name='Дата'),
        ),
    ]
