# Generated by Django 5.1.1 on 2025-02-20 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apt_delivery_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together={('date', 'meal')},
        ),
    ]
