# Generated by Django 5.1.1 on 2025-02-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apt_delivery_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='cod',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
