# Generated by Django 5.1.1 on 2025-03-17 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apt_delivery_app', '0002_alter_menu_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='date',
            field=models.DateField(default=datetime.date(2025, 3, 18), unique=True, verbose_name='Дата'),
        ),
    ]
