# Generated by Django 5.1.1 on 2025-03-04 16:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apt_delivery_app', '0002_alter_menu_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='menu',
            name='date',
            field=models.DateField(default=datetime.date(2025, 3, 5), verbose_name='Дата'),
        ),
        migrations.RemoveField(
            model_name='menu',
            name='meal',
        ),
        migrations.AddField(
            model_name='menu',
            name='meal',
            field=models.ManyToManyField(to='apt_delivery_app.meal', verbose_name='Блюдо'),
        ),
    ]
