# Generated by Django 3.2.25 on 2024-11-21 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_options'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordermeal',
            options={'verbose_name': 'Заказ блюд', 'verbose_name_plural': 'Заказы блюд'},
        ),
        migrations.AddField(
            model_name='order',
            name='cab',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cart.cabinet', verbose_name='Кабинет'),
        ),
        migrations.AlterField(
            model_name='order',
            name='result',
            field=models.CharField(max_length=50, verbose_name='Причина отказа'),
        ),
    ]
