# Generated by Django 3.2.25 on 2025-02-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20250212_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user_comment',
            field=models.TextField(blank=True, help_text='Не обязательное поле', verbose_name='Комментарий пользователя к заказу'),
        ),
    ]
