# Generated by Django 3.2.25 on 2025-01-15 10:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_rename_courier_order_deliver'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата получения заказа'),
        ),
    ]
