# Generated by Django 3.2.25 on 2025-01-16 11:42

import datetime
import django.core.validators
from django.db import migrations, models
import order.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=order.models.get_default_created_at, validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date.today)], verbose_name='Дата и время получения заказа'),
        ),
    ]
