# Generated by Django 3.2.25 on 2025-01-18 16:47

from django.db import migrations, models
import order.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=order.models.get_default_created_at, verbose_name='Дата и время получения заказа'),
        ),
    ]
